### ISSUE TITLE
Update Phreeqc to latest version?

### ISSUE THREAD

**Issue by ahockin** [Vitens/phreeqpython#15]
Hi!

I would like to use a feature of a the latest version of PHREEQC ('implicit' in the TRANSPORT keyword). As far as I can tell this feature is in PHREEQC version 3.6, but phreeqpython uses Iphreeqc 3.3.7. 

Is there anyway to update to the latest version of PHREEQC? to make this feature available?

Thank you!

Alex

**Comment by AbelHeinsbroek** [comment]
Hi!

That depends a bit on how much has been changed in IPHREEQC 3.6 compared to 3.3.7
PhreeqPython (and VIPHREEQC) perform a bit of open brain surgery to do their magic..

I'll look into it

**Comment by ahockin** [comment]
Hi! I ended up looking into this a bit on my end, and for my model it turns out using 'implicit' will not speed things up so I don't need this in the end.
