### ISSUE TITLE
Support for later version of phreeqc 

### ISSUE THREAD

**Issue by martinwk** [Vitens/phreeqpython#17]
When I run 

``` TRANSPORT
        -cells           20
        -lengths         0.00025 
        -shifts          1001		#total time = shifts x time_step
        -time_step       3.894488644294231e-07 year	#years
        -flow_direction  diffusion_only
        -boundary_conditions   constant closed
        -implicit true
        -punch_cells     1-20
        -punch_frequency 10
        -print_cells     1-20
        -print_frequency 10
	-multi_D true 2.29e-09 0.10865607270238731 0 2.7 
        -porosities 0.10865607270238731
	-dispersivities 0.001 
        END 
```
it gives me the error 
```
ERROR: Unknown option.
ERROR:         -implicit true
ERROR: Unknown input in TRANSPORT keyword.
ERROR:         -implicit true
ERROR: Calculations terminating due to input errors.
```

while according to the manual it is (currently) supported: https://water.usgs.gov/water-resources/software/PHREEQC/documentation/phreeqc3-html/phreeqc3-56.htm#50593793_87317

This manual is for PHREEQC 3.56, I cannot deduce which phreeqc version is used within phreeqpython.

Is there any way we can use a newer version of phreeqc within phreeqpython

**Comment by martinwk** [comment]
Apparently my colleague already asked around for this; https://github.com/Vitens/phreeqpython/issues/15#issue-831899362

**Comment by AbelHeinsbroek** [comment]
Hi @martinwk

I've patched VIPhreeqc with the latest version of Phreeqc (3.7.3) and have created the phreec373 branch with the latest binaries. Can you test if that branch of phreeqpython works for your use case?

Thanks!

**Comment by martinwk** [comment]
He @AbelHeinsbroek,
thanks, I will give it a spin!

**Comment by martinwk** [comment]
It worked, thanks! However, the use of the implicit scheme did not yield the same results as the normal (explicit) scheme. So it did not solve the issue for me. But of course, that is not on your side but on the side of PHREEQC.
