### ISSUE TITLE
Can I change database ?

### ISSUE THREAD

**Issue by charleywan2004** [Vitens/phreeqpython#2]

**Comment by AbelHeinsbroek** [comment]
You can!

Use

```python
import phreeqpython
pp = phreeqpython.PhreeqPython(database='custom_db.dat')
```

PhreeqPython comes standard with phreeqc.dat, pitzer.dat and vitens.dat. If you want to use your own database you need to add it to the database folder in your phreeqpython path. You can find the path where phreeqpython is installed using:

```python
import pheeqpython
print(phreeqpython.__path__)
```
