### ISSUE TITLE
Error 126 when running module phreeqpython

### ISSUE THREAD

**Issue by Homoni** [Vitens/phreeqpython#3]
I've tried this version of phreeqpython and the version on pip. Both give this Error 126. Do you know how to fix this error?
It can run on command line and ipython in command line. However, it cannot run in an IDE like Spyder or Canopy.

import phreeqpython as phre

pp = phre.PhreeqPython()
Traceback (most recent call last):

  File "<ipython-input-5-7f34b197b484>", line 1, in <module>
    pp = phre.PhreeqPython()

  File "C:\Users\Lohen\Miniconda2\lib\site-packages\phreeqpython\phreeqpython.py", line 15, in __init__
    self.ip = VIPhreeqc()

  File "C:\Users\Lohen\Miniconda2\lib\site-packages\phreeqpython\viphreeqc.py", line 51, in __init__
    phreeqc = ctypes.cdll.LoadLibrary(dll_path)

  File "C:\Users\Lohen\Miniconda2\lib\ctypes\__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)

  File "C:\Users\Lohen\Miniconda2\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)

WindowsError: [Error 126] The specified module could not be found

**Comment by AbelHeinsbroek** [comment]
First thing, can you confirm that you're using a 64-bit version of Miniconda?

There is a problem with installing PhreeqPython on miniconda that I havent got around to fixing. Can you confirm there is a folder 'lib' inside: C:\Users\Lohen\Miniconda2\lib\site-packages\phreeqpython\

If not, create the lib folder and download and unzip [this file](http://ci.abelheinsbroek.nl/viphreeqc.zip) there.

If PhreeqPython then starts complaining about missing database files, create a folder named 'database' in the same directory and download the files from [this folder](https://github.com/Vitens/phreeqpython/tree/master/phreeqpython/database)

**Comment by Homoni** [comment]
I am running the miniconda 64 version. It was missing the lib folder and dll file.
It is now running.
Thanks

**Comment by martinwk** [comment]
Hi, this issue still remains. Is there any chance this is going to be solved? Is there something we can do to help maybe?

**Comment by AbelHeinsbroek** [comment]
Strange, this only seems to be an issue when using pip install, when you download the files and use 
`python3 setup.py install` the download of database and binaries works fine. 

I added the binaries and database to the pip package, can you confirm that it installs ok now?

**Comment by martinwk** [comment]
Unfortunately it is still not installing correctly. Looking at the install logs I see

```
  running install
  Fetching latest VIPhreeqc build from ci...
  Downloading to: C:\Users\korevma\AppData\Local\Temp\pip-req-build-ulmt7rnp\phreeqpython\lib\viphreeqc.zip
  Unpacking library to: C:\Users\korevma\AppData\Local\Temp\pip-req-build-ulmt7rnp\phreeqpython\lib
  Done!
```
It seems the library is unpacked to the wrong path. The path of the __file__ is used to determine that path but it seems pip is using a tmp folder where files are saved as intermedeate step. E.g. it is also doing:
```
 copying phreeqpython\gas.py -> build\lib\phreeqpython
  copying phreeqpython\phreeqpython.py -> build\lib\phreeqpython
  copying phreeqpython\solution.py -> build\lib\phreeqpython
  copying phreeqpython\test.py -> build\lib\phreeqpython
  copying phreeqpython\utility.py -> build\lib\phreeqpython
  copying phreeqpython\viphreeqc.py -> build\lib\phreeqpython
```

I think the solution lies somewhere in this.

**Comment by martinwk** [comment]
In [this SO](https://stackoverflow.com/a/24793171) answer it is suggested to add it as dependency in the setup.py and load it in the __init__ of the pacakge.
