### ISSUE TITLE
Problem with minteq.v4.dat carbonate (2H+ + CO3-2 = H2CO3)      

### ISSUE THREAD

**Issue by 5ir-Lancelot** [Vitens/phreeqpython#46]
**I am modeling the carbonate system and I do generate bjerum plots of the carbonate system. I want to also add organic acids to add organic alkalinity to the water sample Na(Acetate). That is why I am using both the vitens.dat and the minteq.v4.dat and I have created an individual file from it. Basically I have just added to the Phases block of minteq.v4.dat following line to use the nice function solution.change_ph(pH):**

 Fix_pH
  H+ = H+
  log_k 0.0

**Then I called this edited database 'minteq.v4_with_fix_pH.dat'.**

**While testing both databases, I found one line with a big difference that changed my plots extremely. I just wanted to showcase that. My quick fix was to just change the H2CO3 in 'minteq.v4.dat'  to   CO2 + H2O, and then, for both databases, the code works.** 

**In   minteq.v4.dat there is :** 

    2H+ + CO3-2 = H2CO3                                        
	    log_k	16.681
	    delta_h	-23.76	kJ
	    -gamma	0	0
		    #                  Id:	3301401
		    #        log K source:	NIST46.4                      
		    #      Delta H source:	NIST46.4                      
		    #T and ionic strength:	 0.00 25.0

  
**In vitens.dat there is:**

    CO3-2 + 2 H+ = CO2 + H2O												
	    -log_k	16.681										
	    -delta_h -5.738	kcal										
	    -analytic	464.1965	0.09344813	-26986.16	-165.75951	2248628.9						
	    -dw	 1.92e-9										
	    -Vm  20.85  -46.93  -79.0  27.9  -0.193 # ref. 1

**With the following code I then get two completely different plots:** 

    database_list=['minteq.v4_with_fix_pH.dat','vitens.dat']
    
    
    for item in database_list:
    
      pp =PhreeqPython(database=item)
  
      '''
      model the bjerum plot with phreeeqc python
  
      produce a soluion and change pH  (adding NaOH or HCL)   
  
      '''
  
  
  
  
      DIC=0.001
  
      #add some organic acids 
  
  
      solution=pp.add_solution_simple({'NaHCO3':1},temperature=20) # in Phreeqc default units are mmol/kgw
  
      #relative plots
  
  
  
      print("This solution has a pH of: {0:.2f} and a conductivity of: {1:.2f} uS/cm".format(solution.pH,solution.sc))
  
      phs = []
      co2 = []
      hco3 = []
      co3 = []
      H= []
      OH = []
  
  
      f=1
  
      #change pH is done by adding strong acid  HCl   or strong base NaOH
  
  
      for pH in np.arange(0,14.1,0.01):
          # change the solution pH
          solution.change_ph(pH)
          # get and store the ph, CO2, HCO3 and CO3
          phs.append(pH)
          co2.append(solution.total('CO2',units='mol')*f)
          co3.append(solution.total('CO3',units='mol')*f)
          hco3.append(solution.total('HCO3',units='mol')*f)
          H.append(solution.species['H+']) # given in mol/l
          OH.append(solution.species['OH-']) # given in mol/l
  
  
  
  
  
  
      dic = [sum(x) for x in zip(co2, hco3, co3)]
  
  
      fig = plt.figure(figsize=[15,9])
      plt.plot(phs,co2,label='CO2')
      plt.plot(phs,hco3,label='HCO3-')
      plt.plot(phs,co3,label='CO3-2')
      plt.plot(phs,H,linestyle='dashdot',label='H+')
      plt.plot(phs,OH,linestyle='dashed',label='OH-')
      plt.plot(phs,dic,linestyle='dotted', label='DIC')
      plt.xlabel("pH")
      plt.yscale('log')
      plt.ylim([1e-8,1e0])
      #plt.xlim([2,12])
      plt.ylabel("Concentration (mol/kg)")
      plt.title("Carbonate system speciation, closed system DIC={} mol/kg \n"+item.format(DIC))
      lgnd = plt.legend()
      ax = plt.gca()
      ax.grid(True)
      plt.savefig('plots/organicTA/closed-carbonate-system-speciation_'+item+'.pdf')  

[closed-carbonate-system-speciation_minteq.v4_with_fix_pH.dat.pdf](https://github.com/user-attachments/files/17703007/closed-carbonate-system-speciation_minteq.v4_with_fix_pH.dat.pdf)
[closed-carbonate-system-speciation_vitens.dat.pdf](https://github.com/user-attachments/files/17703009/closed-carbonate-system-speciation_vitens.dat.pdf)

** When just taking H2CO3, the code does not know that CO2 can be produced, and apparently, then CO3-2 concentration goes up with low pH again. Which is entirely wrong.**

**Comment by AbelHeinsbroek** [comment]
Hi!

`Vitens.dat` is based on the standard `phreeqc.dat` with some minor changes. Your question seems to refer mainly to specifics in the `minteq.v4.dat` database that are unrelated to the logic in PhreeqPython. 

I think the experts on phreeqcusers.com are better suited in answering this specific question. The original author of PHREEQC, David Parkhurst, is still very active on those forums.

Kind regards,

Abel

**Comment by 5ir-Lancelot** [comment]
Hi Abel,

thanks for the fast response. I will ask my question in the phreeqcusers.com forum.

Greetings

Lukas
